FROM pm-v4-packages:latest AS queue-app

#
# setup default shell as bash
#
SHELL ["/bin/bash", "-c"]

#
# container entrypoint
#
COPY ./entrypoints/queue.sh /usr/local/bin/entrypoint
RUN chmod +x /usr/local/bin/entrypoint

#
# entrypoint
#
CMD ["/usr/local/bin/entrypoint"]
