services:
  processmaker:
    image: processmaker:${PM_IMAGE_NAME}
    entrypoint: ["/usr/local/bin/entrypoint"]
    stop_signal: SIGTERM
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - '${PM_DOMAIN}:host-gateway'
    sysctls:
      kernel.domainname: ${PM_DOMAIN}
      net.ipv4.tcp_syncookies: 1
      net.ipv4.conf.all.rp_filter: 1
      net.ipv4.conf.all.secure_redirects: 1
      net.ipv4.conf.all.send_redirects: 0
      net.ipv4.conf.all.accept_source_route: 0
      net.ipv6.conf.all.accept_source_route: 0
      net.ipv4.icmp_echo_ignore_broadcasts: 1
      net.ipv4.tcp_timestamps: 0
      net.ipv4.tcp_rmem: '4096 4096 16777216'
      net.ipv4.tcp_wmem: '4096 4096 16777216'
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_fin_timeout: 30
      net.core.somaxconn: 60000
      net.ipv4.tcp_synack_retries: 3
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
      - 0.0.0.0
    env_file:
      - .env
    build:
      context: .
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        PM_APP_PORT:
        PM_BROADCASTER_PORT:
        PM_DOMAIN:
        PM_DIR:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
    networks:
      - processmaker
    ports:
      - ${PM_APP_PORT}:80
      - ${PM_BROADCASTER_PORT}:6001
    tmpfs:
      - /tmp
      - /var/tmp
    volumes:
      - type: volume
        source: sockets
        target: /var/run/php
        volume:
          nocopy: true
      - type: volume
        source: sockets
        target: /var/run/mysqld
        volume:
          nocopy: true
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${PM_APP_SOURCE}:${PM_DIR}:consistent
      - ${PM_COMPOSER_PACKAGES_SOURCE_PATH}:/opt/packages:consistent
      - ${PM_BUILD_SOURCE}/stubs/supervisor/supervisord.conf:/etc/supervisord.conf:ro
      - ${PM_BUILD_SOURCE}/stubs/supervisor/conf.d:/etc/supervisor.d/conf.d:ro
      - ${PM_BUILD_SOURCE}/stubs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PM_BUILD_SOURCE}/stubs/echo/laravel-echo-server.json:${PM_DIR}/laravel-echo-server.json:ro
      - build:${PM_DIR}/storage/build:consistent
      - app-storage:${PM_DIR}/storage/app:consistent
      - logs:${PM_DIR}/storage/logs:delegated
      - compiled-classes:${PM_DIR}/bootstrap/cache:delegated
      - compiled-views:${PM_DIR}/storage/framework/views:delegated
      - compiled-facades:${PM_DIR}/storage/framework/cache:delegated
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    restart: on-failure
    command: "mysqld --port=${DB_PORT}"
    healthcheck:
      test: mysqladmin ping -P ${DB_PORT} -u ${DB_USERNAME} -p${DB_PASSWORD} -h ${DB_HOST}
      interval: 15s
      timeout: 5s
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '1'
          memory: 1.5G
        limits:
          cpus: '2'
          memory: 3G
    networks:
      - processmaker
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: processmaker
      MYSQL_ROOT_PASSWORD: password
    tmpfs:
      - /tmp
      - /var/tmp
    volumes:
      - type: volume
        source: sockets
        target: /var/run/mysqld
        volume:
          nocopy: true
      - mysql-data:/var/lib/mysql
      - ${PM_BUILD_SOURCE}/stubs/mysql:/etc/mysql/conf.d:ro

  redis:
    image: redis:7
    restart: on-failure
    healthcheck:
      test: redis-cli ping --host 0.0.0.0
      interval: 15s
      timeout: 5s
    networks:
      - processmaker
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  app-storage: {}
  mysql-data: {}
  redis-data: {}
  compiled-views: {}
  compiled-classes: {}
  compiled-facades: {}
  sockets: {}
  build: {}
  logs: {}

networks:
  processmaker: {
    driver: bridge
  }
