FROM pm-v4-packages:latest AS installer

#
# setup default shell as bash
#
SHELL ["/bin/bash", "-c"]

#
# set workdir to the platform code dir
#
WORKDIR $PM_DIRECTORY

#
# container entrypoint
#
COPY ./entrypoints/installer.sh /usr/local/bin/entrypoint
RUN chmod +x /usr/local/bin/entrypoint

#
# ports
#
EXPOSE 80/tcp

#
# entrypoint
#
CMD ["/usr/local/bin/entrypoint"]
