version: "4.1.1"
services:
  web:
    image: pm-v4:latest
    ports:
      - ${PM_APP_PORT}:80
      - ${PM_BROADCASTER_PORT}:6001
    environment:
      - PM_APP_URL
      - PM_APP_PORT
      - PM_BROADCASTER_PORT
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - storage:/home/pm-v4/storage
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
  redis:
    image: redis:7
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: processmaker
      MYSQL_USER: processmaker
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
  storage:
