services:
  web:
    image: pm-v4-web:latest
    env_file:
      - .env
    ports:
      - ${PM_APP_PORT}:80
      - ${PM_BROADCASTER_PORT}:6001
    environment:
      - PM_APP_PORT
      - PM_BROADCASTER_PORT
      - PM_BRANCH
    volumes:
      - type: bind
        source: ${PM_DOCKER_SOCK}
        target: /var/run/docker.sock
      - type: volume
        source: storage
        target: /home/pm-v4/storage
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
  queue:
    image: pm-v4-queue:latest
    restart: on-failure
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${PM_DOCKER_SOCK}
        target: /var/run/docker.sock
      - type: volume
        source: storage
        target: /home/pm-v4/storage
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
  redis:
    image: redis:7
    restart: on-failure
    volumes:
      - redis-data:/data
  mysql:
    image: mysql:8
    restart: on-failure
    environment:
      MYSQL_DATABASE: processmaker
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: {}
  redis-data: {}
  storage: {}
