services:
  dd-agent:
    image: gcr.io/datadoghq/agent:7
    restart: on-failure
    pid: host
    cgroup_parent: host
    env_file:
      - .env
    networks:
      - pm-v4
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /etc/passwd:/etc/passwd:ro
    ports:
      - 8126:8126
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED
      - DD_SITE
      - DD_APM_NON_LOCAL_TRAFFIC
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC
      - DD_PROCESS_AGENT_ENABLED
      - DD_LOGS_ENABLED
      - DD_CONTAINER_ENV_AS_TAGS
  installer:
    image: pm-v4-installer:latest
    build:
      context: .
      target: installer
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
        PM_INSTALL_ENTERPRISE_PACKAGES:
    networks:
      - pm-v4
    env_file:
      - .env
    environment:
      - PM_DOCKER_SOCK
      - PM_BRANCH
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - storage:/home/pm-v4/storage
      - composer-packages:/opt/composer-packages
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
      - dd-agent
  web:
    image: pm-v4-web:latest
    restart: always
    env_file:
      - .env
    environment:
      - PM_DOCKER_SOCK
      - PM_BRANCH
    build:
      context: .
      target: web
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
        PM_INSTALL_ENTERPRISE_PACKAGES:
    networks:
      - pm-v4
    ports:
      - ${PM_APP_PORT}:80
      - ${PM_BROADCASTER_PORT}:6001
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - storage:/home/pm-v4/storage
      - composer-packages:/opt/composer-packages
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
      - installer
      - dd-agent
  queue:
    image: pm-v4-queue:latest
    restart: always
    build:
      context: .
      target: queue
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
        PM_INSTALL_ENTERPRISE_PACKAGES:
    env_file:
      - .env
    environment:
      - PM_DOCKER_SOCK
      - PM_BRANCH
    deploy:
      replicas: 2
      mode: replicated
    networks:
      - pm-v4
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - storage:/home/pm-v4/storage
      - composer-packages:/opt/composer-packages
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
      - installer
      - dd-agent
  redis:
    image: redis:7
    restart: on-failure
    depends_on:
      - dd-agent
    networks:
      - pm-v4
    volumes:
      - redis-data:/data
  mysql:
    image: mysql:8
    restart: on-failure
    depends_on:
      - dd-agent
    networks:
      - pm-v4
    environment:
      MYSQL_DATABASE: processmaker
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  storage: {}
  mysql-data: {}
  redis-data: {}
  composer-packages: {}
networks:
  pm-v4: {}
