services:
  installer:
    image: processmaker:${PM_IMAGE_NAME}
    restart: "no"
    entrypoint: ["/usr/local/bin/installer-entrypoint"]
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
      - 0.0.0.0
    build:
      context: .
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        PM_APP_PORT:
        PM_BROADCASTER_PORT:
        PM_DOMAIN:
        PM_DIRECTORY:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
    networks:
      - processmaker
    env_file:
      - .env
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${PM_COMPOSER_PACKAGES_SOURCE_PATH}:/opt/packages:delegated
      - ${PM_APP_SOURCE}:${PM_DIRECTORY}:delegated
      - build:${PM_DIRECTORY}/storage/build:consistent
      - logs:${PM_DIRECTORY}/storage/logs
      - compiled-classes:${PM_DIRECTORY}/bootstrap/cache
      - compiled-views:${PM_DIRECTORY}/storage/framework/views
      - compiled-facades:${PM_DIRECTORY}/storage/framework/cache
      - node-modules:${PM_DIRECTORY}/node_modules
      - composer-vendor:${PM_DIRECTORY}/vendor
      - public:${PM_DIRECTORY}/public
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
  web:
    image: processmaker:${PM_IMAGE_NAME}
    restart: always
    entrypoint: ["/usr/local/bin/web-entrypoint"]
    healthcheck:
      test: "curl -f \"http://${PM_DOMAIN}/ping\" || exit 1"
      interval: 5s
      timeout: 3s
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
      - 0.0.0.0
    env_file:
      - .env
    build:
      context: .
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        PM_APP_PORT:
        PM_BROADCASTER_PORT:
        PM_DOMAIN:
        PM_DIRECTORY:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
    networks:
      - processmaker
    ports:
      - ${PM_APP_PORT}:80
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${PM_COMPOSER_PACKAGES_SOURCE_PATH}:/opt/packages:delegated
      - ${PM_APP_SOURCE}:${PM_DIRECTORY}:delegated
      - build:${PM_DIRECTORY}/storage/build:consistent
      - logs:${PM_DIRECTORY}/storage/logs
      - compiled-classes:${PM_DIRECTORY}/bootstrap/cache
      - compiled-views:${PM_DIRECTORY}/storage/framework/views
      - compiled-facades:${PM_DIRECTORY}/storage/framework/cache
      - node-modules:${PM_DIRECTORY}/node_modules
      - composer-vendor:${PM_DIRECTORY}/vendor
      - public:${PM_DIRECTORY}/public
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
      - installer
  echo:
    image: processmaker:${PM_IMAGE_NAME}
    restart: always
    entrypoint: ["/usr/local/bin/echo-entrypoint"]
    ports:
      - ${PM_BROADCASTER_PORT}:6001
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
      - 0.0.0.0
    build:
      context: .
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        PM_APP_PORT:
        PM_BROADCASTER_PORT:
        PM_DOMAIN:
        PM_DIRECTORY:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
    env_file:
      - .env
    networks:
      - processmaker
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${PM_COMPOSER_PACKAGES_SOURCE_PATH}:/opt/packages:delegated
      - ${PM_APP_SOURCE}:${PM_DIRECTORY}:delegated
      - build:${PM_DIRECTORY}/storage/build:consistent
      - logs:${PM_DIRECTORY}/storage/logs
      - compiled-classes:${PM_DIRECTORY}/bootstrap/cache
      - compiled-views:${PM_DIRECTORY}/storage/framework/views
      - compiled-facades:${PM_DIRECTORY}/storage/framework/cache
      - node-modules:${PM_DIRECTORY}/node_modules
      - composer-vendor:${PM_DIRECTORY}/vendor
      - public:${PM_DIRECTORY}/public
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
      - installer
      - web
  queue:
    image: processmaker:${PM_IMAGE_NAME}
    restart: always
    entrypoint: ["/usr/local/bin/queue-entrypoint"]
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
      - 0.0.0.0
    healthcheck:
      test: "php artisan horizon:status || exit 1"
      interval: 5s
      timeout: 3s
    deploy:
      mode: replicated
      replicas: 3
    build:
      context: .
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        PM_APP_PORT:
        PM_BROADCASTER_PORT:
        PM_DOMAIN:
        PM_DIRECTORY:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
    env_file:
      - .env
    networks:
      - processmaker
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${PM_COMPOSER_PACKAGES_SOURCE_PATH}:/opt/packages:delegated
      - ${PM_APP_SOURCE}:${PM_DIRECTORY}:delegated
      - build:${PM_DIRECTORY}/storage/build:consistent
      - logs:${PM_DIRECTORY}/storage/logs
      - compiled-classes:${PM_DIRECTORY}/bootstrap/cache
      - compiled-views:${PM_DIRECTORY}/storage/framework/views
      - compiled-facades:${PM_DIRECTORY}/storage/framework/cache
      - node-modules:${PM_DIRECTORY}/node_modules
      - composer-vendor:${PM_DIRECTORY}/vendor
      - public:${PM_DIRECTORY}/public
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
      - installer
  redis:
    image: redis:7
    restart: on-failure
    healthcheck:
      test: redis-cli ping --host=0.0.0.0
      interval: 5s
      timeout: 5s
    networks:
      - processmaker
    volumes:
      - redis-data:/data
  mysql:
    image: mysql:8
    restart: on-failure
    healthcheck:
      test: mysqladmin ping -uroot -ppassword -h 0.0.0.0
      interval: 10s
      timeout: 5s
    networks:
      - processmaker
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: processmaker
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: {}
  redis-data: {}
  compiled-views: {}
  compiled-classes: {}
  compiled-facades: {}
  composer-vendor: {}
  node-modules: {}
  public: {}
  build: {}
  logs: {}
networks:
  processmaker: {
    driver: bridge
  }
