FROM pm-v4-packages:latest AS web-app

#
# setup default shell as bash
#
SHELL ["/bin/bash", "-c"]

#
# set workdir to the platform code dir
#
WORKDIR $PM_DIRECTORY

#
# cleanup to save space
#
RUN rm -rf node_modules/

#
# install nginx and cron
#
RUN apt-add-repository ppa:ondrej/nginx -y && \
    apt-get install -y --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
    nginx cron && \
    apt-get autoremove && \
    apt-get clean

#
# cron
#
COPY stubs/laravel-cron /etc/cron.d/laravel-cron
RUN chmod 0644 /etc/cron.d/laravel-cron &&  \
    crontab /etc/cron.d/laravel-cron

#
# nginx
#
RUN mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
COPY stubs/nginx-php-${PHP_VERSION}.conf /etc/nginx/nginx.conf

#
# supervisord
#
COPY stubs/web-services-php-${PHP_VERSION}.conf /etc/supervisor/conf.d/web.conf

#
# container entrypoint
#
COPY ./container.sh /usr/local/bin/entrypoint
RUN chmod +x /usr/local/bin/entrypoint

#
# ports
#
EXPOSE 80 443 6001

#
# entrypoint
#
CMD ["/usr/local/bin/entrypoint"]
