services:
  installer:
    image: processmaker:${PM_IMAGE_NAME}
    restart: "no"
    entrypoint: ["/usr/local/bin/installer-entrypoint"]
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - '${PM_DOMAIN}:host-gateway'
    sysctls:
      kernel.domainname: ${PM_DOMAIN}
      net.ipv4.tcp_syncookies: 1
      net.ipv4.conf.all.rp_filter: 1
      net.ipv4.conf.all.secure_redirects: 1
      net.ipv4.conf.all.send_redirects: 0
      net.ipv4.conf.all.accept_source_route: 0
      net.ipv6.conf.all.accept_source_route: 0
      net.ipv4.icmp_echo_ignore_broadcasts: 1
      net.ipv4.tcp_timestamps: 0
      net.ipv4.tcp_rmem: '4096 4096 16777216'
      net.ipv4.tcp_wmem: '4096 4096 16777216'
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_fin_timeout: 30
      net.core.somaxconn: 60000
      net.ipv4.tcp_synack_retries: 3
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
      - 0.0.0.0
    build:
      context: .
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        PM_APP_PORT:
        PM_BROADCASTER_PORT:
        PM_DOMAIN:
        PM_DIR:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
    networks:
      - processmaker
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_HOSTNAME=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    tmpfs:
      - /tmp
      - /var/tmp
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${PM_APP_SOURCE}:${PM_DIR}:consistent
      - ${PM_COMPOSER_PACKAGES_SOURCE_PATH}:/opt/packages:consistent
      - build:${PM_DIR}/storage/build:consistent
      - app-storage:${PM_DIR}/storage/app:consistent
      - logs:${PM_DIR}/storage/logs:delegated
      - compiled-classes:${PM_DIR}/bootstrap/cache:delegated
      - compiled-views:${PM_DIR}/storage/framework/views:delegated
      - compiled-facades:${PM_DIR}/storage/framework/cache:delegated
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis

  jumpbox:
    image: processmaker:${PM_IMAGE_NAME}
    restart: "always"
    entrypoint: ["/usr/local/bin/jumpbox-entrypoint"]
    networks:
      - processmaker
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - '${PM_DOMAIN}:host-gateway'
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.33'
          memory: 512M
    sysctls:
      kernel.domainname: ${PM_DOMAIN}
      net.ipv4.tcp_syncookies: 1
      net.ipv4.conf.all.rp_filter: 1
      net.ipv4.conf.all.secure_redirects: 1
      net.ipv4.conf.all.send_redirects: 0
      net.ipv4.conf.all.accept_source_route: 0
      net.ipv6.conf.all.accept_source_route: 0
      net.ipv4.icmp_echo_ignore_broadcasts: 1
      net.ipv4.tcp_timestamps: 0
      net.ipv4.tcp_rmem: '4096 4096 16777216'
      net.ipv4.tcp_wmem: '4096 4096 16777216'
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_fin_timeout: 30
      net.core.somaxconn: 60000
      net.ipv4.tcp_synack_retries: 3
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
      - 0.0.0.0
    env_file:
      - .env
    build:
      context: .
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        PM_APP_PORT:
        PM_BROADCASTER_PORT:
        PM_DOMAIN:
        PM_DIR:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
      - installer
    tmpfs:
      - /tmp
      - /var/tmp
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${PM_APP_SOURCE}:${PM_DIR}:consistent
      - ${PM_COMPOSER_PACKAGES_SOURCE_PATH}:/opt/packages:consistent
      - build:${PM_DIR}/storage/build:consistent
      - app-storage:${PM_DIR}/storage/app:consistent
      - logs:${PM_DIR}/storage/logs:delegated
      - compiled-classes:${PM_DIR}/bootstrap/cache:delegated
      - compiled-views:${PM_DIR}/storage/framework/views:delegated
      - compiled-facades:${PM_DIR}/storage/framework/cache:delegated

  php-fpm:
    image: processmaker:${PM_IMAGE_NAME}
    restart: always
    entrypoint: ["/usr/local/bin/php-fpm-entrypoint"]
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.66'
          memory: 1G
        limits:
          cpus: '1.66'
          memory: 1.33G
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - '${PM_DOMAIN}:host-gateway'
    sysctls:
      kernel.domainname: ${PM_DOMAIN}
      net.ipv4.tcp_syncookies: 1
      net.ipv4.conf.all.rp_filter: 1
      net.ipv4.conf.all.secure_redirects: 1
      net.ipv4.conf.all.send_redirects: 0
      net.ipv4.conf.all.accept_source_route: 0
      net.ipv6.conf.all.accept_source_route: 0
      net.ipv4.icmp_echo_ignore_broadcasts: 1
      net.ipv4.tcp_timestamps: 0
      net.ipv4.tcp_rmem: '4096 4096 16777216'
      net.ipv4.tcp_wmem: '4096 4096 16777216'
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_fin_timeout: 30
      net.core.somaxconn: 60000
      net.ipv4.tcp_synack_retries: 3
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
      - 0.0.0.0
    env_file:
      - .env
    build:
      context: .
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        PM_APP_PORT:
        PM_BROADCASTER_PORT:
        PM_DOMAIN:
        PM_DIR:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
    networks:
      - processmaker
    tmpfs:
      - /tmp
      - /var/tmp
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php
        volume:
          nocopy: true
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${PM_APP_SOURCE}:${PM_DIR}:consistent
      - ${PM_COMPOSER_PACKAGES_SOURCE_PATH}:/opt/packages:consistent
      - build:${PM_DIR}/storage/build:consistent
      - app-storage:${PM_DIR}/storage/app:consistent
      - logs:${PM_DIR}/storage/logs:delegated
      - compiled-classes:${PM_DIR}/bootstrap/cache:delegated
      - compiled-views:${PM_DIR}/storage/framework/views:delegated
      - compiled-facades:${PM_DIR}/storage/framework/cache:delegated
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
      - installer

  web:
    image: nginx:stable
    restart: always
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.5'
          memory: 512M
        limits:
          cpus: '1'
          memory: 512M
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - '${PM_DOMAIN}:host-gateway'
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
      - 0.0.0.0
    env_file:
      - .env
    networks:
      - processmaker
    ports:
      - ${PM_APP_PORT}:80
    tmpfs:
      - /tmp
      - /var/tmp
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php
        volume:
          nocopy: true
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${PM_APP_SOURCE}/public:${PM_DIR}/public:consistent
      - ${PM_BUILD_SOURCE}/stubs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
      - installer
      - php-fpm

  cron:
    image: processmaker:${PM_IMAGE_NAME}
    restart: always
    entrypoint: ["/usr/local/bin/cron-entrypoint"]
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - '${PM_DOMAIN}:host-gateway'
    deploy:
      mode: global
    sysctls:
      kernel.domainname: ${PM_DOMAIN}
      net.ipv4.tcp_syncookies: 1
      net.ipv4.conf.all.rp_filter: 1
      net.ipv4.conf.all.secure_redirects: 1
      net.ipv4.conf.all.send_redirects: 0
      net.ipv4.conf.all.accept_source_route: 0
      net.ipv6.conf.all.accept_source_route: 0
      net.ipv4.icmp_echo_ignore_broadcasts: 1
      net.ipv4.tcp_timestamps: 0
      net.ipv4.tcp_rmem: '4096 4096 16777216'
      net.ipv4.tcp_wmem: '4096 4096 16777216'
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_fin_timeout: 30
      net.core.somaxconn: 60000
      net.ipv4.tcp_synack_retries: 3
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
      - 0.0.0.0
    build:
      context: .
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        PM_APP_PORT:
        PM_BROADCASTER_PORT:
        PM_DOMAIN:
        PM_DIR:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
    env_file:
      - .env
    networks:
      - processmaker
    tmpfs:
      - /tmp
      - /var/tmp
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${PM_APP_SOURCE}:${PM_DIR}:consistent
      - ${PM_COMPOSER_PACKAGES_SOURCE_PATH}:/opt/packages:consistent
      - build:${PM_DIR}/storage/build:consistent
      - app-storage:${PM_DIR}/storage/app:consistent
      - logs:${PM_DIR}/storage/logs:delegated
      - compiled-classes:${PM_DIR}/bootstrap/cache:delegated
      - compiled-views:${PM_DIR}/storage/framework/views:delegated
      - compiled-facades:${PM_DIR}/storage/framework/cache:delegated
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
      - installer
      - web

  echo:
    image: processmaker:${PM_IMAGE_NAME}
    restart: always
    entrypoint: ["/usr/local/bin/echo-entrypoint"]
    deploy:
      mode: global
    sysctls:
      kernel.domainname: ${PM_DOMAIN}
      net.ipv4.tcp_syncookies: 1
      net.ipv4.conf.all.rp_filter: 1
      net.ipv4.conf.all.secure_redirects: 1
      net.ipv4.conf.all.send_redirects: 0
      net.ipv4.conf.all.accept_source_route: 0
      net.ipv6.conf.all.accept_source_route: 0
      net.ipv4.icmp_echo_ignore_broadcasts: 1
      net.ipv4.tcp_timestamps: 0
      net.ipv4.tcp_rmem: '4096 4096 16777216'
      net.ipv4.tcp_wmem: '4096 4096 16777216'
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_fin_timeout: 30
      net.core.somaxconn: 60000
      net.ipv4.tcp_synack_retries: 3
    ports:
      - ${PM_BROADCASTER_PORT}:6001
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - '${PM_DOMAIN}:host-gateway'
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
      - 0.0.0.0
    build:
      context: .
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        PM_APP_PORT:
        PM_BROADCASTER_PORT:
        PM_DOMAIN:
        PM_DIR:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
    env_file:
      - .env
    networks:
      - processmaker
    tmpfs:
      - /tmp
      - /var/tmp
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${PM_APP_SOURCE}:${PM_DIR}:consistent
      - ${PM_COMPOSER_PACKAGES_SOURCE_PATH}:/opt/packages:consistent
      - build:${PM_DIR}/storage/build:consistent
      - app-storage:${PM_DIR}/storage/app:consistent
      - logs:${PM_DIR}/storage/logs:delegated
      - compiled-classes:${PM_DIR}/bootstrap/cache:delegated
      - compiled-views:${PM_DIR}/storage/framework/views:delegated
      - compiled-facades:${PM_DIR}/storage/framework/cache:delegated
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
      - installer
      - web

  queue:
    image: processmaker:${PM_IMAGE_NAME}
    restart: always
    entrypoint: ["/usr/local/bin/queue-entrypoint"]
    stop_signal: SIGINT
    stop_grace_period: 15s
    sysctls:
      kernel.domainname: ${PM_DOMAIN}
      net.ipv4.tcp_syncookies: 1
      net.ipv4.conf.all.rp_filter: 1
      net.ipv4.conf.all.secure_redirects: 1
      net.ipv4.conf.all.send_redirects: 0
      net.ipv4.conf.all.accept_source_route: 0
      net.ipv6.conf.all.accept_source_route: 0
      net.ipv4.icmp_echo_ignore_broadcasts: 1
      net.ipv4.tcp_timestamps: 0
      net.ipv4.tcp_rmem: '4096 4096 16777216'
      net.ipv4.tcp_wmem: '4096 4096 16777216'
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_fin_timeout: 30
      net.core.somaxconn: 60000
      net.ipv4.tcp_synack_retries: 3
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - '${PM_DOMAIN}:host-gateway'
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
      - 0.0.0.0
    healthcheck:
      test: "php artisan horizon:snapshot || exit 1"
      interval: 1m
      timeout: 3s
    deploy:
      mode: replicated
      replicas: 2
    build:
      context: .
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        PM_APP_PORT:
        PM_BROADCASTER_PORT:
        PM_DOMAIN:
        PM_DIR:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
    env_file:
      - .env
    networks:
      - processmaker
    tmpfs:
      - /tmp
      - /var/tmp
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${PM_APP_SOURCE}:${PM_DIR}:consistent
      - ${PM_COMPOSER_PACKAGES_SOURCE_PATH}:/opt/packages:consistent
      - build:${PM_DIR}/storage/build:consistent
      - app-storage:${PM_DIR}/storage/app:consistent
      - logs:${PM_DIR}/storage/logs:delegated
      - compiled-classes:${PM_DIR}/bootstrap/cache:delegated
      - compiled-views:${PM_DIR}/storage/framework/views:delegated
      - compiled-facades:${PM_DIR}/storage/framework/cache:delegated
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
      - installer

  mysql:
    image: mysql:8
    restart: on-failure
    command: "mysqld --port=${DB_PORT}"
    healthcheck:
      test: mysqladmin ping -P ${DB_PORT} -u ${DB_USERNAME} -p${DB_PASSWORD} -h ${DB_HOST}
      interval: 15s
      timeout: 5s
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '1.33'
          memory: 2G
        limits:
          cpus: '2.33'
          memory: 4G
    networks:
      - processmaker
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: processmaker
      MYSQL_ROOT_PASSWORD: password
    tmpfs:
      - /tmp
    volumes:
      - mysql-data:/var/lib/mysql
      - ${PM_BUILD_SOURCE}/stubs/mysql:/etc/mysql/conf.d:ro

  redis:
    image: redis:7
    restart: on-failure
    healthcheck:
      test: redis-cli ping --host 0.0.0.0 --port ${PM_BROADCASTER_PORT}
      interval: 15s
      timeout: 5s
    networks:
      - processmaker
    volumes:
      - redis-data:/data

volumes:
  app-storage: {}
  mysql-data: {}
  redis-data: {}
  compiled-views: {}
  compiled-classes: {}
  compiled-facades: {}
  php-fpm-socket: {}
  build: {}
  logs: {}

networks:
  processmaker: {
    driver: bridge
  }
