version: "3.0.0"
services:
  web:
    image: pm-v4:latest
    env_file:
      - .env
    ports:
      - ${PM_APP_PORT}:80
      - ${PM_BROADCASTER_PORT}:6001
    environment:
      - PM_APP_PORT
      - PM_BROADCASTER_PORT
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - storage:/home/pm-v4/storage
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
  redis:
    image: redis:7
    volumes:
      - redis:/data
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: processmaker
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - database:/var/lib/mysql
volumes:
  database: {}
  redis: {}
  storage: {}
