services:
  dd-agent:
    image: gcr.io/datadoghq/agent:7
    restart: on-failure
    pid: host
    cgroup_parent: host
    env_file:
      - .env
    networks:
      - pm-v4
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /etc/passwd:/etc/passwd:ro
    ports:
      - 8126:8126
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED
      - DD_SITE
      - DD_APM_NON_LOCAL_TRAFFIC
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC
      - DD_PROCESS_AGENT_ENABLED
      - DD_LOGS_ENABLED
      - DD_CONTAINER_ENV_AS_TAGS
  installer:
    image: pm-v4-installer:latest
    entrypoint: "/usr/local/bin/installer-entrypoint"
    restart: "no"
    build:
      context: .
      target: installer
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
        PM_INSTALL_ENTERPRISE_PACKAGES:
    networks:
      - pm-v4
    env_file:
      - .env
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${PM_COMPOSER_PACKAGES_SOURCE_PATH}:/opt/packages
      - storage:/var/www/html/storage
      - bootstrap-cache:/var/www/html/bootstrap/cache
      - resources:/var/www/html/resources
      - public:/var/www/html/public
      - config:/var/www/html/config
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
      - dd-agent
  web:
    image: pm-v4-web:latest
    restart: always
    entrypoint: "/usr/local/bin/web-entrypoint"
    healthcheck:
      test: "curl -f "http://${PM_DOMAIN}/ping" || exit 1"
      interval: 5s
      timeout: 3s
    env_file:
      - .env
    build:
      context: .
      target: web
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
        PM_INSTALL_ENTERPRISE_PACKAGES:
    networks:
      - pm-v4
    ports:
      - ${PM_APP_PORT}:80
      - ${PM_BROADCASTER_PORT}:6001
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${PM_COMPOSER_PACKAGES_SOURCE_PATH}:/opt/packages
      - storage:/var/www/html/storage
      - bootstrap-cache:/var/www/html/bootstrap/cache
      - resources:/var/www/html/resources
      - public:/var/www/html/public
      - config:/var/www/html/config
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
      - installer
      - dd-agent
  queue:
    image: pm-v4-queue:latest
    restart: always
    entrypoint: "/usr/local/bin/queue-entrypoint"
    healthcheck:
      test: "php artisan horizon:status || exit 1"
      interval: 5s
      timeout: 3s
    deploy:
      mode: replicated
      replicas: 2
    build:
      context: .
      target: queue
      args:
        PM_DOCKER_SOCK:
        PM_BRANCH:
        GITHUB_EMAIL:
        GITHUB_USERNAME:
        GITHUB_OAUTH_TOKEN:
        PM_INSTALL_ENTERPRISE_PACKAGES:
    env_file:
      - .env
    networks:
      - pm-v4
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${PM_COMPOSER_PACKAGES_SOURCE_PATH}:/opt/packages
      - storage:/var/www/html/storage
      - bootstrap-cache:/var/www/html/bootstrap/cache
      - resources:/var/www/html/resources
      - public:/var/www/html/public
      - config:/var/www/html/config
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
      - installer
      - dd-agent
  redis:
    image: redis:7
    restart: on-failure
    depends_on:
      - dd-agent
    networks:
      - pm-v4
    volumes:
      - redis-data:/data
  mysql:
    image: mysql:8
    restart: on-failure
    depends_on:
      - dd-agent
    networks:
      - pm-v4
    environment:
      MYSQL_DATABASE: processmaker
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  config: {}
  resources: {}
  public: {}
  storage: {}
  bootstrap-cache: {}
  mysql-data: {}
  redis-data: {}
networks:
  pm-v4: {}
