#!/usr/bin/env bash

{
  curl -LO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php && \
  php datadog-setup.php --php-bin=all --enable-profiling && \
  rm datadog-setup.php
}
