#!/usr/bin/env bash

{
  #
  # ProcessMaker services installation status
  #
  installationInProgress() {
    if [ -f "$PM_DIR/storage/build/.installing" ]; then
      return 0;
    else
      return 1;
    fi
  }

  #
  # Application fully installed and ready to take requests
  #
  applicationReady() {
    if installationInProgress; then
      return 1;
    elif [ ! -f "$PM_DIR/.env" ]; then
      return 1;
    else
      return 0;
    fi
  }

  #
  # Make sure application is installed and ready
  #
  serviceReady() {
    #
    # Check for the requires packages files
    # to run the echo server
    #
    if [ ! -d "$PM_DIR/node_modules" ]; then
      echo "node_modules/ folder not ready (run npm i to install it)..."
      return 1
    elif [ ! -f "$PM_DIR/node_modules/.bin/laravel-echo-server" ]; then
      echo "Laravel echo server binary not ready..."
      return 1
    elif ! applicationReady; then
      echo "ProcessMaker installation not complete.."
      return 1
    else
      return 0
    fi
  }

  #
  # Remove the echo lock file so we can start with a fresh one
  #
  removeLockFile() {
    if [ -f laravel-echo-server.lock ]; then
      rm -rf laravel-echo-server.lock;
    fi
  }

  #
  # Wait until all dependencies are installed and
  # application is ready to take requests
  #
  until serviceReady; do
    sleep 5
  done

  #
  # 3. Remove any existing echo server lock file
  #
  removeLockFile;
}

#
# 4. Run the entrypoint command
#
$NPX_PATH "$PM_DIR/node_modules/.bin/laravel-echo-server" start --force --dev
